# Generated by Django 4.2.7 on 2023-11-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author_book_bookinstance_genre_language_delete_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
    ]
